name: root-cpp
version: 0.0.0
homepage: https://github.com/morloclib/root-cpp
synopsis: C++ implementations for root functions
description: C++ implementations for root functions
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/root-cpp
bug-reports: https://github.com/morloclib/root-cpp
